package portal.login.domain;

// Generated 16-giu-2011 14.35.16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Certificate generated by hbm2java
 */
@Entity
@Table(name = "certificate", catalog = "PortalUser")
public class Certificate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4219251531396625106L;
	private int idCert;
	private UserInfo userInfo;
	private String subject;
	private Date expirationDate;
	private String caonline;
	private String primaryCert;
	private String issuer;
	private String usernameCert;

	public Certificate() {
	}

	public Certificate(UserInfo userInfo, String subject, Date expirationDate,
			String caonline, String primaryCert, String issuer,
			String usernameCert) {
		this.userInfo = userInfo;
		this.subject = subject;
		this.expirationDate = expirationDate;
		this.caonline = caonline;
		this.primaryCert = primaryCert;
		this.issuer = issuer;
		this.usernameCert = usernameCert;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCert", unique = true, nullable = false)
	public int getIdCert() {
		return this.idCert;
	}

	public void setIdCert(int idCert) {
		this.idCert = idCert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "subject", nullable = false, length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expirationDate", nullable = false, length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "CAonline", nullable = false, length = 6)
	public String getCaonline() {
		return this.caonline;
	}

	public void setCaonline(String caonline) {
		this.caonline = caonline;
	}

	@Column(name = "primaryCert", nullable = false, length = 6)
	public String getPrimaryCert() {
		return this.primaryCert;
	}

	public void setPrimaryCert(String primaryCert) {
		this.primaryCert = primaryCert;
	}

	@Column(name = "issuer", nullable = false, length = 100)
	public String getIssuer() {
		return this.issuer;
	}

	public void setIssuer(String issuer) {
		this.issuer = issuer;
	}

	@Column(name = "usernameCert", nullable = false, length = 100)
	public String getUsernameCert() {
		return this.usernameCert;
	}

	public void setUsernameCert(String usernameCert) {
		this.usernameCert = usernameCert;
	}

	public boolean equals(Certificate cert) {
		if (this.subject.equals(cert.subject)
				&& this.issuer.equals(cert.issuer))
			return true;
		return false;
	}

}
