package portal.login.domain;

// Generated 16-giu-2011 14.35.16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "userInfo", catalog = "PortalUser")
public class UserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8793989934172666454L;
	private int userId;
	private Idp idp;
	private String firstName;
	private String lastName;
	private String institute;
	private String phone;
	private String mail;
	private String username;
	private String registrationComplete;
	private Set<Certificate> certificates = new HashSet<Certificate>(0);
	private Set<UserToVo> userToVos = new HashSet<UserToVo>(0);

	public UserInfo() {
	}

	public UserInfo(Idp idp, String firstName, String lastName,
			String institute, String mail, String username) {
		this.idp = idp;
		this.firstName = firstName;
		this.lastName = lastName;
		this.institute = institute;
		this.mail = mail;
		this.username = username;
	}

	public UserInfo(Idp idp, String firstName, String lastName,
			String institute, String phone, String mail, String username,
			Set<Certificate> certificates, Set<UserToVo> userToVos) {
		this.idp = idp;
		this.firstName = firstName;
		this.lastName = lastName;
		this.institute = institute;
		this.phone = phone;
		this.mail = mail;
		this.username = username;
		this.certificates = certificates;
		this.userToVos = userToVos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idp", nullable = false)
	public Idp getIdp() {
		return this.idp;
	}

	public void setIdp(Idp idp) {
		this.idp = idp;
	}

	@Column(name = "firstName", nullable = false, length = 75)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 75)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "institute", nullable = false, length = 75)
	public String getInstitute() {
		return this.institute;
	}

	public void setInstitute(String institute) {
		this.institute = institute;
	}

	@Column(name = "phone", length = 75)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mail", nullable = false, length = 75)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "username", nullable = false, length = 75)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "registrationComplete", nullable = false, length = 5)
	public String getRegistrationComplete() {
		return this.registrationComplete;
	}

	public void setRegistrationComplete(String registrationComplete) {
		this.registrationComplete = registrationComplete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<Certificate> getCertificates() {
		return this.certificates;
	}

	public void setCertificates(Set<Certificate> certificates) {
		this.certificates = certificates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<UserToVo> getUserToVos() {
		return this.userToVos;
	}

	public void setUserToVos(Set<UserToVo> userToVos) {
		this.userToVos = userToVos;
	}

}
