package portal.login.domain;

// Generated 16-giu-2011 14.35.16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserToVoId generated by hbm2java
 */
@Embeddable
public class UserToVoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2017618900651289298L;
	private int userId;
	private int idVo;

	public UserToVoId() {
	}

	public UserToVoId(int userId, int idVo) {
		this.userId = userId;
		this.idVo = idVo;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "idVO", nullable = false)
	public int getIdVo() {
		return this.idVo;
	}

	public void setIdVo(int idVo) {
		this.idVo = idVo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserToVoId))
			return false;
		UserToVoId castOther = (UserToVoId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getIdVo() == castOther.getIdVo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getIdVo();
		return result;
	}

}
